### ISSUE TITLE
Will this get updated to 4.17?

### ISSUE THREAD

**Issue by drbo6** [EverNewJoy/UE4GamepadUMG#2]
The plugin works fine but I keep getting an error message about it not matching my engine when loading the project.

**Comment by metahusk** [comment]
I made most of the changes for 4.17 here -> https://github.com/metahusk/UE4GamepadUMG

A pull request has been sent for the changes.

**Comment by drbo6** [comment]
That's excellent. Thanks!

**Comment by EverNewJoy** [comment]
Thanks MetaHusk!

And it was just updated to 4.19 via pull request as well
